### PR TITLE
use slash syntax everywhere

### PR DESCRIPTION
**Pull request by SethTisue**
also bump copyright date and remove redundant license section from readme

### CODE REVIEW

**Comment by SethTisue** [comment]
@dwijnand `import SlashSyntax._` isn't working here... what's the right import?

**Comment by SethTisue** [comment]
Dale spotted the problem:

```
            Global /      sbtVersion  := "1.0.0", // must be Global, otherwise ^^ won't change anything
  LocalRootProject / crossSbtVersions := List("1.0.0"),
```

LOL

**Comment by SethTisue** [comment]
@dwijnand note that CI here is still running on travis-ci.org... time to flip the .com switch

**Comment by dwijnand** [comment]
I ran out of credits on my .com profile.  So when this inevitably actually stops working on .com I'll finally be ~forced~ _motivated_ to learn how to migrate my things to GitHub Actions.

**Comment by SethTisue** [comment]
ah, I see.

anyway, slooooooooow CI likes it, so this is ready for merge, I believe.

**Review by dwijnand — APPROVED** [review]
Thanks, Seth!

**Pull request merged**
