### PR TITLE
Add Sonatype mode

### LINKED ISSUE #53: Can't publish to Sonatype snapshot repository with 400 bad request
`sbt publish` to Sonatype snapshot repository with a dynver string like `0.33.1+1-8ad24f59` fails with 400 error code (bad request). If I use `0.33.1-SNAPSHOT`, there is no problem.

```
[error] (config / publish) java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/org/wvlet/airframe/airframe-config_2.12/0.33.1%2B1-8ad24f59/airframe-config_2.12-0.33.1%2B1-8ad24f59.pom failed with status code 400: Bad Request
[error] (logJVM / publish) java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/org/wvlet/airframe/airframe-log_2.12/0.33.1%2B1-8ad24f59/airframe-log_2.12-0.33.1%2B1-8ad24f59.pom failed with status code 400: Bad Request
```

@dwijnand I'm not sure the expected version path format for Sonatype repository, but if you know a workaround, let me know.

### PR DESCRIPTION
**Pull request by leonardehrenfried**
It turns out easier than I thought. If it is a snapshot then I append -SNAPSHOT.

This one depends on #63 so probably best to review that first.

Fixes #53.

### CODE REVIEW

**Comment by dwijnand** [comment]
This one LGTM. But we need to sort #63 first.

**Comment by olafurpg** [comment]
This is awesome! Thank you @leonardehrenfried

**Comment by mrt181** [comment]
Hi, how do I activate Sonatype mode?

**Comment by qingwei91** [comment]
@mrt181 you can now use `dynverSonatypeSnapshots := true` 

I am only able to make it work by doing `dynverSonatypeSnapshots in ThisBuild := true`, I am not sure why

**Pull request merged**
