### PR TITLE
Allow arbitrary prefixes for tags

### PR DESCRIPTION
**Pull request by sideeffffect**
This PR builds on top of https://github.com/dwijnand/sbt-dynver/pull/62 by @eliaslevy to bring to `sbt-dynver` the ability to work with arbitrary prefixes for git tags.
This effectively allows a particular sbt configuration to focus only on a subset of all the tags in the repository.
This is useful when working with multiple projects in one git repository (monorepo-like), when for example some of the projects might not even use `sbt-dynver` or even use sbt or even be written in Scala.

The PR is as minimalistic as possible and is backwards compatible, especially with regards to the behavior of `dynverVTagPrefix`.

Could you @dwijnand please review this? :pray:

### CODE REVIEW

**Comment by dwijnand** [comment]
Hmm, like in #62, things not being defined in build-scope is a big drawback.  I'll try to find time to review this more.

**Comment by sideeffffect** [comment]
I'm no sbt expert, but I guess things being defined in project scope (and not build scope) is a natural consequence of each project (possibly) having different prefix and thus version. Is my understanding correct? If yes, then I'm afraid there's nothing I can do about that bit.
But I'd be happy to refactor things to have this feature merged! (I love sbt-dynver and how it makes versioning a single sbt project a breeze and I would like to use it at work in a git repo with multiple projects, but that is currently not possible :crying_cat_face: )

**Comment by dwijnand** [comment]
I think, for my own sake, I'm going to have to do something I've rarely done: just refuse a feature/enhancement.  I just don't feel like undertaking the effort to support the "multiple projects in the same git repo" feature/scenario.  Sorry.

If you feel like it would be correct to make this explicit in the README and/or if you would like a spot in the README to mention alternatives to sbt-dynver that support that case, I'd be happy to merge those PRs.

**Comment by sideeffffect** [comment]
I see your point @dwijnand that having things defined at project-scope (and not build-scope) is problematic. Here's the thing, I only did that, because that's how @eliaslevy did it in his original PR and I wanted to respect that. But now I see that approach would put an unreasonable burden on you/the sbt-dynver project and I respect that too.
And I personally actually don't need having things at project-scope and treating each sbt sub-project differently (which would require to move things out of build-scope). I just need to customize the tag prefix.

So here's what I did: I moved things back to build-scope, so things are back to normal, one can configure sbt-dynver with `... in ThisBuild` or `inThisBuild(...)` as before. But now one can customize the prefix of the tag, which I think is a conservative extension of the current `dynverVTagPrefix` mechanism (which keeps on working, btw).

Please let me know what you think and if you would consider this a reasonable compromise.
Best regards

**Comment by dwijnand** [comment]
Yep, a custom tag prefix for the whole build sounds fine.  Basically a generalised version of "dynverVTagPrefix".

**Comment by sideeffffect** [comment]
Hello @dwijnand , can I gently ask if you would perhaps have some time soon to review this PR? Thank you :smiley:

**Comment by dwijnand** [comment]
My apologies.  I was waiting for news on this, because I hadn't noticed the commit push before your last comment.

I'll try to review this this weekend.

**Comment by sideeffffect** [comment]
Hello @dwijnand, I would like remind myself with the prefix PR. Thanks :smile_cat:

**Comment by dwijnand** [comment]
I've been head-first in Zinc code for about 6 days, so I didn't get a chance.  I've got a long weekend come up, so I'll try to spend time on this.

**Comment by sideeffffect** [comment]
> head-first in Zinc code

thank you for all the amazing work you're doing @dwijnand :muscle: :+1:

**Comment by sideeffffect** [comment]
Those are great news @dwijnand :tada: 
Could you please make a release, so that we can use this new feature?
Thank you once again :smiley:

**Comment by dwijnand** [comment]
Yep, releasing 4.1.0 first thing Monday, if nothing urgent happens.

**Pull request merged**
