### PR TITLE
Match on lightweight and containing only major version tags

### LINKED ISSUE #7: A tag of "v2" isn't matched
There's an error in the `--match` flag to git describe.

It should be `--match v[0-9]*` rather than `--match v[0-9]*`.

### PR DESCRIPTION
**Pull request by 2m**
Fixes #7 and #14

### CODE REVIEW

**Comment by dwijnand** [comment]
Thanks!

**Comment by 2m** [comment]
Thanks for merging. It would be great, if you could cut a release with this fix.

**Comment by dwijnand** [comment]
Well! Thanks to the fact that I have TravisCI publish for me, this was available to be used even before I merged it :-)

`addSbtPlugin("com.dwijnand" % "sbt-dynver" % "1.0.0+15-3655d014")`

But I will cut a 1.1.0 release, just not tonight - I'm exhausted after releasing sbt 0.13.13 today..

**Comment by 2m** [comment]
Ah right. This is sbt plugin and it is enough to have it published in bintray. Thats good enough for me. :)

**Comment by dwijnand** [comment]
It's actually possible to do for releases to Maven Central too. I've just don't have a project that needs it.

**Comment by 2m** [comment]
How would you go about automatically releasing to Maven Central? AFAIK releasing to Sonatype repo requires a manual step of closing the repo. And releasing to Bintray requires a manual step to sync to Maven Central.

**Comment by dwijnand** [comment]
[sonatypeRelease](https://github.com/xerial/sbt-sonatype#sbt-sonatype-plugin) and [bintraySyncMavenCentral](https://github.com/softprops/bintray-sbt/blob/0.3.0/src/main/scala/BintrayKeys.scala#L62-L63)

**Comment by 2m** [comment]
Solutions to both of the manual steps, nice. Which one do you prefer? I am currently figuring out automated release process for akka/alpakka and I am doing it through bintray with the sole advantage that I do not need to have encrypted pgp signing keys in the repo: bintray can sign the artifacts itself.

**Comment by dwijnand** [comment]
I like Bintray because it's instantly available, and because I use it for sbt-plugins.

**Pull request merged**
