### PR TITLE
Add support for looking up a previous stable version's tag

### PR DESCRIPTION
**Pull request by MaxwellBo**

### CODE REVIEW

**Comment by dwijnand** [comment]
Hi @MaxwellBo! Could you explain what the motivation for this feature is?

**Comment by MaxwellBo** [comment]
Hi @dwijnand - sincerest apologies for the delay! We're currently using `previousStableVersion` with `mimaReportBinaryIssues`, so that any every version is compatibility checked against the previous (assumed) release. We guessed that this might be a common use-case for `sbt-dynver`.

**Comment by jatcwang** [comment]
I'm working one this with Max. There are some more improvements we want to make. Will update the PR (or raise another) when we're done

**Comment by dwijnand** [comment]
Superseded by #50

**Pull request closed without merging**
