### PR TITLE
Append +0 to first dirty version after tag

### LINKED ISSUE #52: Versioning compatibility with ivy2/maven wildcard patterns for first snapshot build after tag
I'm loving this plugin, but I'm looking for a way to easily use it with dependency wildcard patterns in ivy and maven.

the current versioning pattern means that the first "snapshot" version after a tag is `0.0.1+20171207-1200` ; while the first committed version after a tag is `0.0.1+1-01234abcd`

This means that a version spec like "0.0.1+" will select the older, snapshot, version over the newer version.

This could be solved just by changing the first snapshot build after a tag to use `0.0.1+0+20171207-1200`

I know I can customize my version string - but this seems like a wide use case.

### LINKED ISSUE #53: Can't publish to Sonatype snapshot repository with 400 bad request
`sbt publish` to Sonatype snapshot repository with a dynver string like `0.33.1+1-8ad24f59` fails with 400 error code (bad request). If I use `0.33.1-SNAPSHOT`, there is no problem.

```
[error] (config / publish) java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/org/wvlet/airframe/airframe-config_2.12/0.33.1%2B1-8ad24f59/airframe-config_2.12-0.33.1%2B1-8ad24f59.pom failed with status code 400: Bad Request
[error] (logJVM / publish) java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/org/wvlet/airframe/airframe-log_2.12/0.33.1%2B1-8ad24f59/airframe-log_2.12-0.33.1%2B1-8ad24f59.pom failed with status code 400: Bad Request
```

@dwijnand I'm not sure the expected version path format for Sonatype repository, but if you know a workaround, let me know.

### PR DESCRIPTION
**Pull request by leonardehrenfried**
I wanted to fix #53 but you asked for #52 to be fixed first, so this adds a `+0` for dirty snapshots directly after a tag.

In the original bug ticket you say that you also want to add `+0000` but I'm confused by this. There was also the suggestion about adding the commit SHA, too.

Can you elaborate what should be there?

Fixes #52.

### CODE REVIEW

**Comment by raboof** [comment]
Thanks for taking the time to look into this!

So with this change a dirty repository on a tag has a version like `1.0.0+0-20140707-1030`, and after a couple of commits it would be something like `1.0.0+3-1234abcd-20140707-1030`. It might be nice to make those 2 even more consistent by including the `headSha` in both cases, so the dirty repository on the tag would be like `1.0.0+0-abab2323-20140707-1030`.

What do you think?

**Comment by dwijnand** [comment]
I think @xerial's suggestion (https://github.com/dwijnand/sbt-dynver/issues/53#issuecomment-355364899) is even better than my original one:

> Instead of using 0000000 (+0 commit), we should use the actual revision like:
> 
>     1.0.0+0-xxxxxxx-20140707-1030
> 
> This is more informative to tell which git revision is used.

To that end I think all that is needed is dropping the `isEmpty` from `GitCommitSuffixOps`'s `mkString`.

**Comment by leonardehrenfried** [comment]
I'm happy implementing this but I'm wondering: Aren't you two (@raboof, @dwijnand) suggesting the same thing?

**Comment by raboof** [comment]
I think we're in violent agreement here, yes ;)

**Comment by dwijnand** [comment]
Yep! Arnout's comment hadn't loaded in my tab by the time I got round to leaving my comment.

**Comment by leonardehrenfried** [comment]
I took a first stab at implementing this. The problem is that the output of git describe doesn't contain the SHA1 information. Should I get it from a second call to git?

**Comment by laughedelic** [comment]
@leonardehrenfried probably you need to use `--long` option?

```
$ git describe
v2.0.2
$ git describe --long
v2.0.2-0-gd0b6f72
```

**Comment by leonardehrenfried** [comment]
I didn't know about --long but it looks exactly like what we need. We can
use that output as is without any magic checking it seems.

I'll try it out.

Am 19.02.2018 10:17 nachm. schrieb "Alexey Alekhin" <
notifications@github.com>:

**Comment by laughedelic** [comment]
Take into account that it has an extra letter `g` before the commit SHA and abbreviation is 7 letters by default. I don't know if you can remove `g`, but you can add `--abbrev=8` if you need.

**Comment by dwijnand** [comment]
We use `--abbrev=8` and manage the extra `g` already: https://github.com/dwijnand/sbt-dynver/blob/v2.1.0/src/main/scala/sbtdynver/DynVerPlugin.scala#L125-L127

Good find on `--long`!

**Comment by leonardehrenfried** [comment]
I think this is good for another round of reviews.

I removed the `isEmpty` check completely and moved all the if statements into `GitDescribeOutput` instead.

**Comment by leonardehrenfried** [comment]
But I still think this ready to merge.

**Comment by laughedelic** [comment]
@leonardehrenfried could you also update [the readme](https://github.com/dwijnand/sbt-dynver#detail)?

**Comment by dwijnand** [comment]
Thanks @leonardehrenfried. I'll try to get to this tomorrow.

**Pull request merged**
